'use client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { Toaster } from 'react-hot-toast'
import 'react-loading-skeleton/dist/skeleton.css'
import { RecoilRoot } from 'recoil'
import { AppProvider } from './AppProvider'
import './fonts.css'
import './global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false,
      refetchOnWindowFocus: false,
      refetchOnMount: false,
    },
  },
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body>
        <QueryClientProvider client={queryClient}>
          <RecoilRoot>
            <AppProvider>{children}</AppProvider>
            <Toaster />
            <ReactQueryDevtools initialIsOpen={false} />
          </RecoilRoot>
        </QueryClientProvider>
      </body>
    </html>
  )
}
