'use client'
import { SavedUser } from '@pynspel/types'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { useEffect } from 'react'
import { Toaster } from 'react-hot-toast'
import 'react-loading-skeleton/dist/skeleton.css'
import { RecoilRoot } from 'recoil'
import { useGuildService } from '~/hooks/useGuildService'
import { userGuildsProxy, userProxy } from '~/proxys/user'
import { fetchApi } from '~/utils/fetchApi'
import { AppProvider } from './AppProvider'
import './fonts.css'
import './global.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      retry: false,
      refetchOnWindowFocus: false,
      refetchOnMount: false,
    },
  },
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { getMutualGuilds } = useGuildService()

  useEffect(() => {
    const handleFetchUser = async () => {
      const res = await fetchApi<SavedUser>(`/api/users/me`)

      userProxy.isAuthenticated = true
      userProxy.user = res

      const mutualGuilds = await getMutualGuilds()

      userGuildsProxy.guilds = mutualGuilds
    }

    handleFetchUser()
  }, [])

  return (
    <html lang="fr">
      <body>
        <QueryClientProvider client={queryClient}>
          <RecoilRoot>
            <AppProvider>{children}</AppProvider>

            <Toaster />
            <ReactQueryDevtools initialIsOpen={false} />
          </RecoilRoot>
        </QueryClientProvider>
      </body>
    </html>
  )
}
